language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.4.*"
    - SYMFONY_VERSION="4.1.*"
    - SYMFONY_VERSION="4.2.*"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - phpenv config-rm xdebug.ini
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
  - php composer.phar update --prefer-stable --prefer-lowest

notifications:
  email:
    - bartlomiej.ojrzenski@pixers.pl
